# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebef146083d1369a7c02e8decf0441bc178e7024302f0f263d499e963ba12291e308a96b649a0e5fe6602f741a93ef1e910bcd0ade3060969069e538951ffb57

test:
  secret_key_base: 72669a635eebb4acc3ec0aacfd6395450ac8d55ce808ce5f83eebe278411c2028ae43c5e19d5b94ea6b3faa03fd7fadf5f027b7d5a5c4d6c045d2a93f002c0b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
